In [1]:
import numpy as np
import pandas as pd

***One Hot Encoding***

In [2]:
labels = np.array(["cat", "dog", "mat", "rat", "sat", "cat", "hat", "fat", "hat", "sat"]).reshape(-1, 1)
labels.flatten()

array(['cat', 'dog', 'mat', 'rat', 'sat', 'cat', 'hat', 'fat', 'hat',
       'sat'], dtype='<U3')

In [3]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output=False)
builtin_encodings = ohe.fit_transform(labels)

def onehot(labels):
    encodings = []
    sorted_labels = set(np.unique(labels))
    sorted_labels = list(sorted(sorted_labels))
    total_labels = len(sorted_labels)

    for label in labels:
        encoding = [0] * total_labels
        index = sorted_labels.index(label)
        encoding[index] = 1
        encodings.append(encoding)
    
    return np.array(encodings)

custom_encodings = onehot(labels)
builtin_encodings, custom_encodings

(array([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1.]]),
 array([[1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1]]))

***Bag of Words (BoW)***

In [4]:
statements = np.array([
    "cat catch the mat that catch hat",
    "rat match hat dog catch hat",
    "sat on the dog cat sat on rat",
    "dog catch cat dog fat fat",
    "fat rat run match rat"
])
statements

array(['cat catch the mat that catch hat', 'rat match hat dog catch hat',
       'sat on the dog cat sat on rat', 'dog catch cat dog fat fat',
       'fat rat run match rat'], dtype='<U32')

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

bow = CountVectorizer()
builtin_bow = bow.fit_transform(statements).toarray()

def bow(statements):
    vocabulary = set()
    for statement in statements:
        words = statement.split(' ')
        for word in words:
            vocabulary.add(word)

    vocabulary = sorted(vocabulary)
    vocab_size = len(vocabulary)

    encodings = []
    for statement in statements:
        encoding = [0] * vocab_size
        words = statement.split(' ')
        for word in words:
            encoding[ vocabulary.index(word) ] += 1
        encodings.append(encoding)
    
    return encodings

custom_bow = bow(statements)
builtin_bow, custom_bow

(array([[1, 2, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1],
        [0, 1, 1, 0, 2, 0, 1, 0, 1, 0, 0, 0, 0],
        [1, 0, 1, 0, 0, 0, 0, 2, 1, 0, 2, 0, 1],
        [1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 1, 0, 2, 1, 0, 0, 0]]),
 [[1, 2, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1],
  [0, 1, 1, 0, 2, 0, 1, 0, 1, 0, 0, 0, 0],
  [1, 0, 1, 0, 0, 0, 0, 2, 1, 0, 2, 0, 1],
  [1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 1, 0, 0, 1, 0, 2, 1, 0, 0, 0]])