In [1]:
import numpy as np
import pandas as pd
import sklearn 
import tensorflow as tf
import matplotlib.pyplot as plt

In [2]:
labels = np.array(["cat", "dog", "mouse", "cat", "dog", "cat", "cat"]).reshape(-1, 1)
records, _ = labels.shape
labels, records

(array([['cat'],
        ['dog'],
        ['mouse'],
        ['cat'],
        ['dog'],
        ['cat'],
        ['cat']], dtype='<U5'),
 7)

### One Hot Encoding

In [3]:
# Library

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)
onehot = encoder.fit_transform(labels)
onehot

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [4]:
# Scratch

vocab = list(sorted(set(labels.flatten().copy())))
vocab_size = len(vocab)
onehot = np.array([ [ 0 for _ in range(vocab_size) ] for _ in range(records) ])

for i in range(records):
    label = labels[i, 0]
    index = vocab.index(label)
    onehot[i, index] += 1

onehot

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0]])

### Bag of Words

In [5]:
# Scratch

statements = [
    "cat mat sat",
    "rat sat dog mat",
    "cat dog sat"
]

vocab = set( word for stat in statements for word in stat.split(' ')  )
vocab = sorted(vocab)

vocab_size, max_length = len(vocab), max(len(stat) for stat in statements)

bow = []
for stat in statements:
    code = [0] * vocab_size
    for word in stat.split(' '):
        index = vocab.index(word)
        code[index] = 1
    bow.append(code)
    
np.array(bow)

array([[1, 0, 1, 0, 1],
       [0, 1, 1, 1, 1],
       [1, 1, 0, 0, 1]])

In [6]:
# Library
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
ans = vectorizer.fit_transform(statements)
ans.toarray()

array([[1, 0, 1, 0, 1],
       [0, 1, 1, 1, 1],
       [1, 1, 0, 0, 1]])