In [1]:
"""
4. Implement TFIDF, BOW and One hot Encoding vectorization from scratch using numpy 
only. 
"""

'\n4. Implement TFIDF, BOW and One hot Encoding vectorization from scratch using numpy \nonly. \n'

In [2]:
import numpy as np

### One Hot Encoding

In [3]:
documents = np.array([
    "cat", "dog", "mouse", "cat", "dog", "cat", "cat"
])

def onehot(labels):  
    sorted_labels = np.sort(labels)
    sorted_labels = np.unique(sorted_labels).tolist()

    length = len(sorted_labels)
    encodings = []

    for label in labels:
        code = np.array([0] * length)
        code[ sorted_labels.index(label) ] = 1
        encodings.append(code)

    return np.array(encodings)

encodings = onehot(documents)
encodings

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0]])

### Bag Of Words

In [4]:
documents = [
    "cat mat sat",
    "rat sat dog mat sat dog sat",
    "cat dog sat"
]

def bow(documents):
    vocabulary = []
    for doc in documents:
        for word in doc.split(' '):
            vocabulary.append(word) 

    vocabulary = np.array(list(vocabulary))
    vocabulary = np.unique(vocabulary)
    
    vocabulary = np.sort(vocabulary).tolist()
    length = len(vocabulary)

    encodings = []
    for doc in documents:
        code = [0] * length
        for word in doc.split(' '):
            code[ vocabulary.index(word) ] += 1
        encodings.append(code)
            
    return np.array(encodings)

encodings = bow(documents)
encodings

array([[1, 0, 1, 0, 1],
       [0, 2, 1, 1, 3],
       [1, 1, 0, 0, 1]])

### TF-IDF 

In [5]:
documents_tags = [
    ["marry", "jane", "can", "see", "will", " "],
    ["will", "jane", "spot", "marry"],
    ["spot", "will", "see", "marry"],
    ["marry", "will", "pat", "spot"]
]

def tf_idf(documents):
    # Term Frequency = words in sentance / total word appearance
    word_frequency = dict()
    for doc in documents:
        for word in doc:
            if word in word_frequency:
                word_frequency[word] += 1
            else:
                word_frequency[word] = 1

    tfs = []
    for doc in documents:
        tf = []
        for word in doc:
            tf.append( doc.count(word) / word_frequency[word] )
        tfs.append(tf)

    # IDF = log( 1 + total_documents / word appearance in document )
    document_frequency_word = dict()
    for word in word_frequency.keys():
        count = 0
        for doc in documents: 
            count += 1 if doc.count(word) > 0 else 0
        document_frequency_word[word] = count
    
    idfs = []
    total_documents = len(documents)
    for doc in documents:
        idf = []
        for word in doc:
            idf.append(np.log( (1+total_documents) / document_frequency_word[word] ))
        idfs.append(idf)

    tf_idfs = []
    for doc_index in range(len(documents)):
        tf_idf = []
        for index in range(len(documents[doc_index])):
            tf_idf.append( float(tfs[doc_index][index] * idfs[doc_index][index]) )
        tf_idfs.append(np.array(tf_idf))

    return tf_idfs

tf_idf(documents_tags)

[array([0.05578589, 0.45814537, 1.60943791, 0.45814537, 0.05578589,
        1.60943791]),
 array([0.05578589, 0.45814537, 0.17027521, 0.05578589]),
 array([0.17027521, 0.05578589, 0.45814537, 0.05578589]),
 array([0.05578589, 0.05578589, 1.60943791, 0.17027521])]